### ISSUE TITLE
Add SSR support

### ISSUE THREAD

**Issue by macwac** [bitworking/react-scrollmagic#1]
I use this package with next.js but i got error ReferenceError: window is not defined.
I'm trying use this package https://github.com/kadirahq/react-no-ssr and still not working. I'm new in react and I have no idea to solve the problem

**Comment by bitworking** [comment]
I've tried it now several hours and don't get it. I've tried dynamic imports with stage-3 babel in componentDidMount but that doesn't help either. It keeps getting these window errors.

Perhaps tomorrow I'm trying again, but my plan was to build another modern scrolling library because ScrollMagic is not maintained anymore since 3 or 4 years.

**Comment by macwac** [comment]
Thanks for your replay. I found soulution for next.js https://github.com/zeit/next.js/pull/1750 I use noSSR support method for component where i use react-scrollmagic

**Comment by bitworking** [comment]
Ok nice. But in this way it doesn't render on server side? So the complete markup is not in the sourcecode, right?

**Comment by macwac** [comment]
Yes, dynamic components are splitted to webpack chunks

**Comment by joperron** [comment]
I've been looking at this for a little bit because I ran into the same issue with Gatsby and I wish there was an equivalent to `noSSR` like next.js has!

**Comment by bitworking** [comment]
I'm working at version 2 right now and I there I wrapped the whole ScrollMagic library in a self invoking function so that I can mock the window and document object. Seems to work fine and I probably will release it this evening.

**Comment by bitworking** [comment]
Version 2 is out now. It should work with Gatsby and Next.js.
