### ISSUE TITLE
Example for nested controller and scenes

### ISSUE THREAD

**Issue by jacargentina** [bitworking/react-scrollmagic#7]
Hi again! I cant yet complete my homepage prototype: i'm struggling on understanding how the Controller and Scene work, especially in the case for multiple Controllers.

I'm trying something like, having this `example/src/components/ScrollMagicExamples/SectionWipes.js` as the main scrolling scenes, but then on any of those sub-panes, having a **nested controller** with its own animation during scrolling: in my case i want to have the panes as the **sections for my homepage**, and then one of those is **_"Who We Are"_** section, in which i want to make **fade in sequence** the 4 team members for my company, while the user is scrolling. After finishing it, then it goes to the next section (Pane) with other info.

@bitworking  can you post some working example for reference please?

**Comment by bitworking** [comment]
This should work for you: https://stackblitz.com/edit/react-bmmavx

I found a problematic code in react-gsap which only allows Tween components (displayName=Tween) to be controlled by Timelime components. This makes it hard to create for example a base `FadeIn` component and reuse it. That's why I added the `tweenProps` object to each Tween component.

**Comment by bitworking** [comment]
@jacargentina 

I've updated the example. With pushFollowers: false, duration: 100% and margin-bottom: 100% on the panel it works.

**Comment by jacargentina** [comment]
@bitworking Simply GREAT!

BTW, would you please elaborate a little on some details? The `margin-bottom: 1000px` seems a very important detail for this to work, for example.
